global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ai-optimizer-app'
    scheme: https
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ai-optimizer.onrender.com']
