spring:
  application:
    name: Admin Dashboard Backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' or 'none' in production
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  main:
    allow-bean-definition-overriding: true

  web:
    cors:
      allowed-origins: ${CORS_ORIGINS}
      allowed-methods: ${CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
      allowed-headers: ${CORS_HEADERS:Authorization,Content-Type}
      allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

    resources:
      add-mappings: true
  mvc:
    # throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

logging:
  level:
    org.springframework.security: DEBUG
